package org.vinni.cliente.gui;

import org.vinni.dto.MiDatagrama;

import javax.swing.*;
import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * author: Vinni 2024
 */
public class PrincipalCli extends JFrame {

    private final int PORT_SERVIDOR = 12345;
    private DatagramSocket canal;

    private static final int TamanhoT = 512;
    private static final long tamanhoMin = 1024;
    private static final long tamanhoMax = 5 * 1024 * 1024;
    private static final String[] extensionesProhividas = {".exe", ".bat"};

    private final java.util.Map<String, java.util.Map<Integer, byte[]>> recibidos = new java.util.concurrent.ConcurrentHashMap<>();
    private final java.util.Map<String, Integer> totalesRecibidos = new java.util.concurrent.ConcurrentHashMap<>();

    /**
     * Creates new form Principal1
     */
    public PrincipalCli() {
        initComponents();

        this.btEnviar.setEnabled(true);
        this.mensajesTxt.setEditable(false);

        try {
            canal = new DatagramSocket();
            this.setTitle("Cliente  —  Mi puerto: " + canal.getLocalPort());
            escucharRespuestas();
        } catch (SocketException ex) {
            Logger.getLogger(PrincipalCli.class.getName()).log(Level.SEVERE, null, ex);
        }



        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                try {
                    String despedida = "DESCONECTAR:" + canal.getLocalPort();
                    DatagramPacket p = MiDatagrama.crearDataG("127.0.0.1", PORT_SERVIDOR, despedida);
                    canal.send(p);
                } catch (IOException ex) { /* ignorar */ }
            }
        });
    }

/** Hilo que escucha los mensajes broadcast que reenvia el servidor */
private void escucharRespuestas() {
    new Thread(() -> {
        byte[] buf = new byte[1024];
        while (true) {
            DatagramPacket dp = new DatagramPacket(buf, buf.length);
            try {
                canal.receive(dp);
                String msg = new String(dp.getData(), 0, dp.getLength());

                if (msg.startsWith("CLIENTE_NUEVO:")) {
                    String direccion = msg.substring("CLIENTE_NUEVO:".length()).trim();
                    SwingUtilities.invokeLater(() -> agregarClienteAlCombo(direccion));
                } else if (msg.startsWith("CLIENTE_DESCONECTADO:")) {
                    String direccion = msg.substring("CLIENTE_DESCONECTADO:".length()).trim();
                    SwingUtilities.invokeLater(() -> quitarClienteDelCombo(direccion));
                } else if (msg.startsWith("FILE|")) {
                    procesarChunkRecibido(msg);
                } else {
                    SwingUtilities.invokeLater(() -> mensajesTxt.append(msg + "\n"));
                }

            } catch (IOException ex) {
                Logger.getLogger(PrincipalCli.class.getName()).log(Level.SEVERE, null, ex);
                break;
            }
        }
    }).start();
}


    private void agregarClienteAlCombo(String direccion) {
        String propio = "127.0.0.1:" + canal.getLocalPort();
        if (direccion.equals(propio)) return;

        for (int i = 0; i < comboDestino.getItemCount(); i++) {
            if (comboDestino.getItemAt(i).equals(direccion)) return;
        }
        comboDestino.addItem(direccion);
    }

    private void quitarClienteDelCombo(String direccion) {
        comboDestino.removeItem(direccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        btEnviarArchivo = new JButton("Enviar Archivo");
        btEnviarArchivo.setFont(new java.awt.Font("Verdana", 0, 12));
        btEnviarArchivo.addActionListener(e -> seleccionarYEnviarArchivo());
        getContentPane().add(btEnviarArchivo);
        btEnviarArchivo.setBounds(180, 160, 140, 27);

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jScrollPane1 = new JScrollPane();
        mensajesTxt = new JTextArea();
        mensajeTxt = new JTextField();
        comboDestino = new JComboBox<>();
        btEnviar = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("CLIENTE UDP : LUING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 250, 17);

        mensajesTxt.setColumns(20);
        mensajesTxt.setRows(5);

        jScrollPane1.setViewportView(mensajesTxt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 210, 410, 110);

        comboDestino.addItem("-- Todos (broadcast) --");
        comboDestino.setFont(new java.awt.Font("Verdana", 0, 12));
        comboDestino.setToolTipText("Selecciona un cliente destino o broadcast");
        getContentPane().add(comboDestino);
        comboDestino.setBounds(105, 45, 330, 25);

        mensajeTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(mensajeTxt);
        mensajeTxt.setBounds(40, 120, 350, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Mensaje:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 120, 30);

        btEnviar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.addActionListener(e -> enviarMensaje());
        getContentPane().add(btEnviar);
        btEnviar.setBounds(327, 160, 120, 27);

        setSize(new java.awt.Dimension(491, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new PrincipalCli().setVisible(true));
    }

    private void seleccionarYEnviarArchivo() {
        String seleccion = (String) comboDestino.getSelectedItem();
        String destino = (seleccion == null || seleccion.startsWith("--")) ? "ALL" : seleccion;

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccionar archivo para enviar a " + destino);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int resultado = chooser.showOpenDialog(this);
        if (resultado != JFileChooser.APPROVE_OPTION) return;

        File archivo = chooser.getSelectedFile();

        String nombreLower = archivo.getName().toLowerCase();
        for (String ext : extensionesProhividas) {
            if (nombreLower.endsWith(ext)) {
                JOptionPane.showMessageDialog(this, "No se permiten archivos con extensión '" + ext + "'",
                        "Extensión no permitida", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        long tamanoBytes = archivo.length();
        if (tamanoBytes < tamanhoMin) {
            JOptionPane.showMessageDialog(this, "El archivo es demasiado pequeño.\nTamaño mínimo: 1 KB",
                    "Archivo muy pequeño", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (tamanoBytes > tamanhoMax) {
            JOptionPane.showMessageDialog(this, "El archivo supera el límite permitido.\nTamaño máximo: 5 MB",
                    "Archivo muy grande", JOptionPane.WARNING_MESSAGE);
            return;
        }

        btEnviarArchivo.setEnabled(false);
        mensajesTxt.append("[ARCHIVO] Preparando envío de " + archivo.getName() + " a " + destino + "...\n");

        new Thread(() -> {
            try {
                byte[] bytes = java.nio.file.Files.readAllBytes(archivo.toPath());
                String nombre = archivo.getName();

                String ext = nombre.contains(".") ? nombre.substring(nombre.lastIndexOf('.') + 1).toLowerCase() : "";
                String nombreSinExt = nombre.contains(".") ? nombre.substring(0, nombre.lastIndexOf('.')) : nombre;
                String transferId = java.util.UUID.randomUUID().toString().substring(0, 8);

                int total = (int) Math.ceil((double) bytes.length / TamanhoT);

                for (int i = 0; i < total; i++) {
                    int desde = i * TamanhoT;
                    int hasta = Math.min(desde + TamanhoT, bytes.length);
                    byte[] fragmento = java.util.Arrays.copyOfRange(bytes, desde, hasta);
                    String b64 = java.util.Base64.getEncoder().encodeToString(fragmento);

                    // FILE|transferId|nombre|ext|total|idx|destino|b64data
                    String msg = "FILE|" + transferId + "|" + nombreSinExt + "|"
                            + ext + "|" + total + "|" + i + "|" + destino + "|" + b64;

                    DatagramPacket paquete = MiDatagrama.crearDataG("127.0.0.1", PORT_SERVIDOR, msg);
                    canal.send(paquete);

                    Thread.sleep(2);
                }

                SwingUtilities.invokeLater(() ->
                        mensajesTxt.append("[ARCHIVO] Enviado al servidor: " + nombre + " -> " + destino + "\n")
                );

            } catch (Exception ex) {
                SwingUtilities.invokeLater(() ->
                        mensajesTxt.append("[ERROR] Al leer o enviar el archivo: " + ex.getMessage() + "\n")
                );
            } finally {
                SwingUtilities.invokeLater(() -> btEnviarArchivo.setEnabled(true));
            }
        }).start();
    }


    private void procesarChunkRecibido(String msg) {
        // FILE|transferId|nombre|ext|total|idx|destino|remitente|b64data
        String[] p = msg.split("\\|", 9);
        if (p.length < 9) return;

        String transferId = p[1];
        String nombre = p[2];
        String ext = p[3];
        int total = Integer.parseInt(p[4]);
        int idx = Integer.parseInt(p[5]);
        String remitente = p[7];
        byte[] datos = java.util.Base64.getDecoder().decode(p[8]);

        recibidos.computeIfAbsent(transferId, k -> new java.util.concurrent.ConcurrentHashMap<>()).put(idx, datos);
        totalesRecibidos.put(transferId, total);

        if (recibidos.get(transferId).size() == total) {
            try {
                java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
                for (int i = 0; i < total; i++) baos.write(recibidos.get(transferId).get(i));
                byte[] datosCompletos = baos.toByteArray();

                recibidos.remove(transferId);
                totalesRecibidos.remove(transferId);

                SwingUtilities.invokeLater(() -> {
                    String nombreArchivo = nombre + (ext.isEmpty() ? "" : "." + ext);
                    mensajesTxt.append("[ARCHIVO] De " + remitente + ": " + nombreArchivo + " — Elige dónde guardar...\n");

                    JFileChooser chooser = new JFileChooser();
                    chooser.setDialogTitle("Guardar archivo de " + remitente);
                    chooser.setSelectedFile(new File(nombreArchivo));
                    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

                    int resultado = chooser.showSaveDialog(this);
                    if (resultado == JFileChooser.APPROVE_OPTION) {
                        File destino = chooser.getSelectedFile();
                        try {
                            java.nio.file.Files.write(destino.toPath(), datosCompletos);
                            mensajesTxt.append("[ARCHIVO] Guardado en: " + destino.getAbsolutePath() + "\n");
                        } catch (IOException e) {
                            mensajesTxt.append("[ERROR] No se pudo guardar: " + e.getMessage() + "\n");
                        }
                    } else {
                        mensajesTxt.append("[ARCHIVO] Guardado cancelado.\n");
                    }
                });

            } catch (IOException ex) {
                Logger.getLogger(PrincipalCli.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void enviarMensaje() {
        String mensaje = mensajeTxt.getText().trim();
        if (mensaje.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay mensaje para enviar");
            return;
        }

        String seleccion = (String) comboDestino.getSelectedItem();

        try {
            if (seleccion == null || seleccion.startsWith("--")) {
                DatagramPacket paquete = MiDatagrama.crearDataG("127.0.0.1", PORT_SERVIDOR, mensaje);
                canal.send(paquete);
            } else {
                // PRIVADO
                String[] partes = seleccion.split(":");
                String ip = partes[0];
                int puerto = Integer.parseInt(partes[1].trim());

                String msgFormateado = "[DIRECTO de mi:" + canal.getLocalPort() + "] " + mensaje;
                DatagramPacket paquete = MiDatagrama.crearDataG(ip, puerto, msgFormateado);
                canal.send(paquete);

                mensajesTxt.append("[ID -> " + seleccion + "] " + mensaje + "\n");
            }

            mensajeTxt.setText("");

        } catch (IOException ex) {
            Logger.getLogger(PrincipalCli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify
    private JButton btEnviarArchivo;
    private JButton btEnviar;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JScrollPane jScrollPane1;
    private JTextArea mensajesTxt;
    private JTextField mensajeTxt;
    private JComboBox<String> comboDestino;
    // End of variables declaration
}

//vlhkbkbv aca 1 2 3