package org.vinni.cliente.gui;

import org.vinni.dto.MiDatagrama;

import javax.swing.*;
import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * author: Vinni 2024
 */
public class PrincipalCli extends JFrame {

    private final int PORT_SERVIDOR = 12345;
    private DatagramSocket canal;


    /**
     * Creates new form Principal1
     */
    public PrincipalCli() {
        initComponents();

        this.btEnviar.setEnabled(true);
        this.mensajesTxt.setEditable(false);

    try {
        canal = new DatagramSocket();
        this.setTitle("Cliente  —  Mi puerto: " + canal.getLocalPort());
        escucharRespuestas();
    } catch (SocketException ex) {
        Logger.getLogger(PrincipalCli.class.getName()).log(Level.SEVERE, null, ex);
    }
}

/** Hilo que escucha los mensajes broadcast que reenvia el servidor */
private void escucharRespuestas() {
    new Thread(() -> {
        byte[] buf = new byte[1024];
        while (true) {
            DatagramPacket dp = new DatagramPacket(buf, buf.length);
            try {
                canal.receive(dp);
                String msg = new String(dp.getData(), 0, dp.getLength());

                if (msg.startsWith("CLIENTE_NUEVO:")) {
                    String direccion = msg.substring("CLIENTE_NUEVO:".length()).trim();
                    SwingUtilities.invokeLater(() -> agregarClienteAlCombo(direccion));
                } else if (msg.startsWith("CLIENTE_DESCONECTADO:")) {
                    String direccion = msg.substring("CLIENTE_DESCONECTADO:".length()).trim();
                    SwingUtilities.invokeLater(() -> quitarClienteDelCombo(direccion));
                } else {
                    SwingUtilities.invokeLater(() -> mensajesTxt.append(msg + "\n"));
                }


            } catch (IOException ex) {
                Logger.getLogger(PrincipalCli.class.getName()).log(Level.SEVERE, null, ex);
                break;
            }
        }
    }).start();
}


    private void agregarClienteAlCombo(String direccion) {
        for (int i = 0; i < comboDestino.getItemCount(); i++) {
            if (comboDestino.getItemAt(i).equals(direccion)) return;
        }
        comboDestino.addItem(direccion);
    }

    private void quitarClienteDelCombo(String direccion) {
        comboDestino.removeItem(direccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jScrollPane1 = new JScrollPane();
        mensajesTxt = new JTextArea();
        mensajeTxt = new JTextField();
        comboDestino = new JComboBox<>();
        btEnviar = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);



        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("CLIENTE UDP : LUING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 250, 17);

        mensajesTxt.setColumns(20);
        mensajesTxt.setRows(5);

        jScrollPane1.setViewportView(mensajesTxt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 210, 410, 110);

        comboDestino.addItem("-- Todos (broadcast) --");   // opción por defecto
        comboDestino.setFont(new java.awt.Font("Verdana", 0, 12));
        comboDestino.setToolTipText("Selecciona un cliente destino o broadcast");
        getContentPane().add(comboDestino);
        comboDestino.setBounds(105, 45, 330, 25);

        mensajeTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(mensajeTxt);
        mensajeTxt.setBounds(40, 120, 350, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Mensaje:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 120, 30);

        btEnviar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.addActionListener(e -> enviarMensaje());
        getContentPane().add(btEnviar);
        btEnviar.setBounds(327, 160, 120, 27);

        setSize(new java.awt.Dimension(491, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new PrincipalCli().setVisible(true));
    }

    // Variables declaration - do not modify

    private JButton btEnviar;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JScrollPane jScrollPane1;
    private JTextArea mensajesTxt;
    private JTextField mensajeTxt;
    private JComboBox<String> comboDestino;
    // End of variables declaration


    private void enviarMensaje() {
        String mensaje = mensajeTxt.getText().trim();
        if (mensaje.isEmpty()){
            JOptionPane.showMessageDialog(this,"No hay mensaje para enviar");
            return ;
        }

        String seleccion = (String) comboDestino.getSelectedItem();

        String mensajeFinal;
        if (seleccion == null || seleccion.startsWith("--")) {
            mensajeFinal = mensaje;
        } else {
            mensajeFinal = "@" + seleccion + " " + mensaje;
        }

        try {
            DatagramPacket paquete = MiDatagrama.crearDataG(
                    "127.0.0.1", PORT_SERVIDOR, mensajeFinal);
            canal.send(paquete); // reutiliza el mismo socket (mismo puerto)
            mensajeTxt.setText(""); // limpiar campo tras enviar
        } catch (IOException ex) {
            Logger.getLogger(PrincipalCli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

